ChainID = '59140'
FinalityDepth = 1
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '6m'

[GasEstimator]
PriceMin = '20 mwei'
BumpPercent = 20

[GasEstimator.BlockHistory]
BlockHistorySize = 12

[HeadTracker]
HistoryDepth = 50